// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/branding/IconRail.tsx": () => import("../components/mockups/branding/IconRail.tsx"),
  "./components/mockups/branding/IndustrialAccent.tsx": () => import("../components/mockups/branding/IndustrialAccent.tsx"),
  "./components/mockups/branding/NavHeader.tsx": () => import("../components/mockups/branding/NavHeader.tsx"),
  "./components/mockups/branding/SplitCenter.tsx": () => import("../components/mockups/branding/SplitCenter.tsx")
};
